### PR TITLE
BLD: Update Dockerfile to install gramex from conda

### LINKED ISSUE #321: Compilation failure in docker image
**Is something not working as expected?**
`/ui/bootstraptheme.css` is broken in the latest docker image.

When running gramex in the gramener/gramex docker image (latest, v1.65), on the latest branch of the guide,

**Steps to reproduce.**
1. Pull the latest (v1.65) docker image
2. Run the guide (latest master) from within the image
3. Visit `/uicomponents`

This produces:
```
node-sass error: b'/opt/conda/lib/python3.7/site-packages/gramex/apps/ui/node_modules/node-sass/lib/binding.js:15\n      throw new Error(errors.missingBinary());\n      ^\n\nError: Missing binding /opt/conda/lib/python3.7/site-packages/gramex/apps/ui/node_modules/node-sass/vendor/linux-x64-64/binding.node\nNode Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x\n\nFound bindings for the following environments:\n  - Linux 64-bit with Node.js 14.x\n\nThis usually happens because your environment has changed since running `npm install`.\nRun `npm rebuild node-sass` to download the binding for your current environment.\n    at module.exports (/opt/conda/lib/python3.7/site-packages/gramex/apps/ui/node_modules/node-sass/lib/binding.js:15:13)\n    at Object.<anonymous> (/opt/conda/lib/python3.7/site-packages/gramex/apps/ui/node_modules/node-sass/lib/index.js:14:35)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/opt/conda/lib/python3.7/site-packages/gramex/apps/ui/node_modules/node-sass/bin/node-sass:10:10)\n'
ERROR   02-Nov 05:48:15 web Uncaught exception GET /ui/bootstraptheme.css (172.17.0.1)
HTTPServerRequest(protocol='http', host='localhost:9988', method='GET', uri='/ui/bootstraptheme.css', version='HTTP/1.1', remote_ip='172.17.0.1')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.7/site-packages/gramex/handlers/functionhandler.py", line 60, in _get
    item = yield item
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/conda/lib/python3.7/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/opt/conda/lib/python3.7/site-packages/gramex/apps/ui/__init__.py", line 73, in sass
    raise RuntimeError('Compilation failure')
RuntimeError: Compilation failure
ERROR   02-Nov 05:48:15 __init__ 9988 500 GET /ui/bootstraptheme.css (172.17.0.1) 641.70ms apps/ui/bootstrap4-Ie8d9
```

### PR DESCRIPTION
**Pull request by jaidevd**
Fixes #321

### CODE REVIEW

**Comment by sanand0** [comment]
@jaidevd I made a few small changes, ran the build, and pushed. Could you please check if it's working?

**Comment by jaidevd** [comment]
@sanand0 Works well except pandoc is missing from the Dockerfile, adding that and testing again.

**Comment by jaidevd** [comment]
@sanand0 Works now.

**Comment by sanand0** [comment]
Thanks. I'll merge.

Why is pandoc required, though?

**Comment by jaidevd** [comment]
@sanand0 I vaguely remember it being needed for r-markdown.
travis.yml has it as an apt package. I'll test it sometime, though .

**Pull request merged**
