### PR TITLE
ENH: Chart data columns positional identifiers changes.

### PR DESCRIPTION
**Pull request by nivedita-deshmukh**
**Purpose: Using column position as well assign the color to a column from ".yaml" definition.**

Here is the sample ".yaml" example

```
chart_name:
  chart:
    data:
      function: >
        py_file.py_func(data['test_data'], handler)
          x: 'label'
            color:
              2: '#B9CDE5'
              3: '#558ED5'
```

### CODE REVIEW

**Comment by pratapvardhan** [comment]
@nivedita-deshmukh -- could you add test case to understand the usecase better? Or share the reproducible example? input pptx, output pptx, same data -- attach these in the comment, if you're unable to add a test case.

**Comment by nivedita-deshmukh** [comment]
@pratapvardhan PFA of test data and ppt on the below link
[https://drive.google.com/open?id=1WC9YbCv1R1oL0WR090qBbX8c8VlLZ5tU](url)

**Comment by nivedita-deshmukh** [comment]
@pratapvardhan please do let me know if anything else more require.

**Comment by pratapvardhan** [comment]
@nivedita-deshmukh would explore [Register a new command to PPTGen](https://learn.gramener.com/guide/pptxhandler/#register-register-a-new-command-to-pptgen) as an alternative.

**Pull request closed without merging**
