### PR TITLE
GRAMEX-126 ⁃ ServiceNow plugin added to gramex for filtering

### PR DESCRIPTION
**Pull request by radheyakale**
┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-126)

### CODE REVIEW

**Comment by radheyakale** [comment]
The yaml file will be as follows:
url:
  sample_servicenow:
    pattern: /$YAMLURL/sample_servicenow
    handler: FormHandler
    kwargs:
      url: 'servicenow://'
      instance: 'dev100943'
      user: 'admin'
      password: '******'
      api_path: '/table/incident'

**Comment by sanand0** [comment]
Great!!

Could you test out the following features and see which ones work and which ones don't? Based on that, we can take a call on whether we need to implement any other features.

- [ ] ?Continent=Europe ► Continent = Europe
- [ ] ?Continent=Europe&Continent=Asia ► Continent = Europe OR Asia. Multiple values are allowed
- [ ] ?Continent!=Europe ► Continent is NOT Europe
- [ ] ?Continent!=Europe&Continent!=Asia ► Continent is NEITHER Europe NOR Asia
- [ ] ?Shapes ► Shapes is not NULL
- [ ] ?Shapes! ► Shapes is NULL
- [ ] ?c1>=10 ► c1 > 10 (not >= 10)
- [ ] ?c1>~=10 ► c1 >= 10. The ~ acts like an =
- [ ] ?c1<=10 ► c1 < 10 (not <= 10)
- [ ] ?c1<~=10 ► c1 <= 10. The ~ acts like an =
- [ ] ?c1>=10&c1<=20 ► c1 > 10 AND c1 < 20
- [ ] ?Name~=United ► Name matches &_format=html
- [ ] ?Name!~=United ► Name does NOT match United
- [ ] ?Name~=United&Continent=Asia ► Name matches United AND Continent is Asia
- [ ] Limit rows: ?_limit=10 ► show only 10 rows
- [ ] Offset rows: ?_offset=10&_limit=10 ► show only 10 rows starting, skipping the first 10 rows
- [ ] Sort by columns: ?_sort=Continent&_sort=Name ► sort first by Continent (ascending) then Name (ascending)
- [ ] Sort order: ?_sort=-Continent&_sort=-ID ► sort first by Continent (descending) then ID (descending)
- [ ] Specific columns: ?_c=Continent&_c=Name ► show only the Continent and Names columns
- [ ] Exclude columns: ?_c=-Continent&_c=-Name ► show all columns except the Continent and Names columns
- [ ] Add metadata: ?_meta=y ► return all available metadata as HTTP headers
- [ ] ?_by=Text: group by Text, and sum all numeric columns.
- [ ] ?_by=Text&_by=Symbols: group by Text and by Symbols.
- [ ] ?_by=Continent&_c=Name|count: group by Continent, count names of countries
- [ ] ?_by=Continent&_c=Name|count&_c=c1|min&_c=c1|avg&_c=c1|max

**Comment by sanand0** [comment]
Next steps:

- Add documentation (anywhere) on how to create a sample ServiceNow instance and how to install pysnow
- Please have @LaxmiShivannavar test all the scenarios listed above (without any guidance other than the docs above)
- Once that's done, I'll do the same.
- We'll move the docs into the Guide and merge

**Comment by radheyakale** [comment]
1. For creating a ServiceNow developer instance, kindly visit https://developer.servicenow.com/dev.do and click on "Signup and Start building".
2. After your account is successfully created and verified, Sign in to the account and ensure that you have admin access by clicking on the user profile on the top right corner. User Role should display Admin. If not, click on Change User Role-> Admin.
3. Once that's done, click on "Start Building".
4. Username should be "admin", password would be your account password. Your browser's URL would be <instance_variable>.service-now.com.
5. In your gramex.yaml file, add the following FormHandler:

url:
  sample_servicenow:
    pattern: /$YAMLURL/sample_servicenow
    handler: FormHandler
    kwargs:
      url: 'servicenow://'
      instance: 'dev100943' ----> This instance would <instance_variable> as shown in step 4.
      user: 'admin'
      password: '********' ----> Enter your account's password here
      api_path: '/table/incident' ----> As we would be accessing the incident table (https://dev100943.service-now.com/api/now/table/incident)

6. You'll now be able to access data on localhost:9988/sample_servicenow and use the filters checked above viz. localhost:9988/sample_servicenow?_sort=number for sorting and so on.

7. Kindly note that you would have to visit https://developer.servicenow.com/dev.do before accessing the API and ensure that the instance is not hibernated. If so, click on "Start Building"; which will wake up the instance.

**Comment by LaxmiShivannavar** [comment]
Few points needs to be added in the Document, and they are listed below,

1. While User signsup to "ServiceNow" he has to select "Yes, I need a developer oriented IDE" in order to change the User Role to "admin".

**Pull request closed without merging**
