### PR TITLE
GRAMEX-175 ⁃ ENH: Add support for statsmodels.SARIMAX in MLHandler

### PR DESCRIPTION
**Pull request by jaidevd**
Post https://github.com/gramener/gramex/pull/507, this version of the statsmodels API is available via the
wrapper classes for MLHandler, instead of being in the handler itself.

┆Issue is synchronized with this [Jira Bug](https://gramenertech.atlassian.net/browse/GRAMEX-175)

### CODE REVIEW

**Comment by jaidevd** [comment]
Not to be merged before #519

**Comment by sanand0** [comment]
Got this error

```
======================================================================
ERROR: test_sarimax (tests.test_mlhandler.TestStatsmodels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\site\gramener.com\viz\async-gramex\tests\test_mlhandler.py", line 51, in test_sarimax
    data[['year', 'quarter']].apply(lambda x: '%dQ%d' % (x.year, x.quarter), axis=1)
  File "D:\anaconda\3.7\lib\site-packages\numpy\core\records.py", line 456, in __getattribute__
    raise AttributeError("recarray has no attribute %s" % attr) from e
AttributeError: recarray has no attribute apply
```

**Comment by jaidevd** [comment]
Looks like the version of statsmodels has to be pinned. But it's required only for the tests. Where do we specify test dependencies?

**Comment by jaidevd** [comment]
@sanand0 What's your statsmodels version? Mine is 0.13.2 - on which these tests work.

**Comment by jaidevd** [comment]
Add statsmodels in tests/requirements.txt

**Pull request merged**
