### PR TITLE
Make psycopg2 optional

### PR DESCRIPTION
**Pull request by jaidevd**
On a clean Ubuntu 16.04 setup with nothing except miniconda, gramex
installation fails due to the missing  pg_config executable which is
required by psycopg2

### CODE REVIEW

**Comment by pratapvardhan** [comment]
Or should we move database libraries to setup.py's `tests_require`?

**Comment by jaidevd** [comment]
CRAN seems to be down.

**Comment by jaidevd** [comment]
@pratapvardhan is there something to be done here?

**Comment by pratapvardhan** [comment]
I'll remove the commented line. Merge it in the upcoming release. No changes required.

**Comment by samrudh** [comment]
The same issue in fresh MAC setup with nothing installed previously:

A quick fix that worked: Installing **postgresql**

`brew install postgresql`

**Comment by pratapvardhan** [comment]
fixed via 801a25f

**Comment by pratapvardhan** [comment]
Fixed via 801a25f

**Pull request closed without merging**
