### PR TITLE
Add support for offsets in MSSQL

### LINKED ISSUE #65: Form Handler: _offset is not working with MSSQL Server
**_Yaml Config:_**

```yaml
  path_name:
    pattern: /$YAMLURL/urlpattern
    handler: FormHandler
    kwargs:
      auth: {login_url: /$YAMLURL/login/}
      url: $dbstring
      table: tablename
      id: [id]
```

**_url pattern:_** [localhost:9981/urlpattern?_offset=12000&_limit=15000](url)

**_Throwing this error_**

image

### PR DESCRIPTION
**Pull request by jaidevd**
Closes #65 

Summary of the solution:

* If the dialect is `'mssql'` and either `'_limit'` or `_offset'` are present in `controls`, then force sort by the first column in the table
* Create a row number over this column, hide it later
* Use this column to implement offset with limits.

### CODE REVIEW

**Comment by sanand0** [comment]
Too much additional code for an edge case, @jaidevd -- I'd like to rethink this. Will defer to milestone 1.52 please

**Comment by jaidevd** [comment]
Sure, @sanand0.

**Comment by sanand0** [comment]
@jaidevd please see how much of this can be solved at the application level (e.g. ensure that `?_sort=` is always present). Whatever is the minimal change to Gramex required after that can be in this PR.

**Comment by jaidevd** [comment]
Please take a look, @jpsiyyadri

**Pull request closed without merging**
