### PR TITLE
Python 3.8 + Gramex

### PR DESCRIPTION
**Pull request by bkamapantula**

### CODE REVIEW

**Comment by jaidevd** [comment]
@bkamapantula This branch doesn't seem to have a makefile - which is there on the master. Is this branch up-to-date with master?

**Comment by bkamapantula** [comment]
@jaidevd updated with latest master (uifactory was earlier merged in the day and a few days ago)

**Comment by jaidevd** [comment]
Please mention on guide/r that all R packages are to be installed from conda-forge, for Python 3.8:

```bash
conda install -c conda-forge rpy2 r-ggplot2 r-rmarkdown
```

**Comment by bkamapantula** [comment]
thanks @jaidevd @pratapvardhan! 

@sanand0 this is ready for review

python 3.8, pandas 0.25.3, tornado 5.1.1

**Comment by bkamapantula** [comment]
closing this in favor of #399

**Pull request closed without merging**
